name: Plug-in CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm

            - run: npm ci --registry=https://registry.npmjs.org/
            - run: npx tsc -p src/bootstrap/tsconfig.json --noEmit
            - run: npx tsc -p src/worker/tsconfig.json --noEmit
            - run: npm run build-dev

            - name: Upload development build
              if: github.event_name == 'push'
              uses: actions/upload-artifact@v4
              with:
                  name: chartero-dev-xpi
                  path: build/chartero.xpi
                  if-no-files-found: error

    dev-release:
        if: github.event_name == 'push'
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Download development build
              uses: actions/download-artifact@v4
              with:
                  name: chartero-dev-xpi
                  path: build

            - name: Release development build
              uses: softprops/action-gh-release@v2
              with:
                  name: Development Build
                  tag_name: dev
                  prerelease: true
                  make_latest: false
                  generate_release_notes: true
                  append_body: |
                      For testing purposes only, do not use in production. ![cnt](https://img.shields.io/github/downloads/Step2312/Chartero/dev/total)
                  files: build/chartero.xpi
