name: Plug-in CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm

            - run: npm ci --registry=https://registry.npmjs.org/
            - run: npx tsc -p src/bootstrap/tsconfig.json --noEmit
            - run: npx tsc -p src/worker/tsconfig.json --noEmit
            - run: npm run build-dev

            - name: Upload development build
              if: github.event_name == 'push'
              uses: actions/upload-artifact@v4
              with:
                  name: chartero-dev-xpi
                  path: build/chartero.xpi
                  if-no-files-found: error
